### PR TITLE
chore: modernize Fly setup

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
See https://github.com/remix-run/indie-stack/pull/253, https://github.com/remix-run/blues-stack/pull/201 & https://github.com/remix-run/react-router-website/pull/74

---

#104 should be merged first

### CODE REVIEW

**Comment by dev-xo** [comment]
Hello @MichaelDeBoey! 

First of all, thank you so much for the time invested into this commits!
Second thing, gonna have a look at them, and probably them will be merged.

Wanna let you know that the stack will change a lot with the release from Remix v2, 
so I had no intention to keep investing that much on it until that.

In any case, thanks for this little updates. I really appreciate it!

**Comment by MichaelDeBoey** [comment]
@dev-xo If you want help with the v2 changes, I'm happy to help out

**Comment by dev-xo** [comment]
All right, will let you know @MichaelDeBoey!
Thanks again for the PRs!

**Comment by dev-xo** [comment]
Merged 3/4 PRs @MichaelDeBoey. 
Sadly this one isn't being able to pass the Fly Deploy run.

It throws error: `Process completed with exit code 127` Check: [Failed Action](https://github.com/dev-xo/stripe-stack/actions/runs/5963673466/job/16177579628)

The other PRs passed successfully and ended up deploying to fly.
Any idea about what this could be?

**Comment by dev-xo** [comment]
Ah never-mind, #104 should have been merged first right? My bad I guess!

**Comment by MichaelDeBoey** [comment]
@dev-xo Fixed in #106

**Comment by dev-xo** [comment]
Fixed! Again, thank you so much for the time you've set into this @MichaelDeBoey!
It's a time you choose to spend on a project to improve the community, and that's kinda awesome!

Thank you! <3

**Pull request merged**
